### ISSUE TITLE
How to use array of json values in single html file?

### ISSUE THREAD

**Issue by sharmmoh1983** [farrukhmpk/html-pdf-service#3]

**Comment by farrukhmpk** [comment]
Array of JSON values is not supported at the moment, this is one thing that I have been meaning to work on but haven't gotten a chance yet.
You are more than welcome to contribute by implementing a repeatableView tag.

**Comment by farrukhmpk** [comment]
This feature request has now been added.
This feature is implemented by <repeat></repeat> tags inside the html and have an array inside the JSON object. 
The service allows multiple repeat tags in a document, but currently does not support nested repeat tags.

This means the service allows the user to have a multiple tables.
The table can be dynamically populated based on JSON data with either multiple rows or multiple columns but not both.

Hope this helps.

**Comment by farrukhmpk** [comment]
Closing as implemented
